"""Conversation states. Stored in Supabase, never in process memory."""

IDLE = "IDLE"

# registration
REG_NAME = "REG_NAME"
REG_ROLL = "REG_ROLL"
REG_DATE = "REG_DATE"
REG_SHIFT = "REG_SHIFT"
REG_CATEGORY = "REG_CATEGORY"
REG_CENTRE = "REG_CENTRE"

# submission
SUB_GK_ATT = "SUB_GK_ATT"
SUB_GK_MARKS = "SUB_GK_MARKS"
SUB_EN_ATT = "SUB_EN_ATT"
SUB_EN_MARKS = "SUB_EN_MARKS"
SUB_CONFIRM = "SUB_CONFIRM"

# answer key upload
KEY_AWAIT_FILE = "KEY_AWAIT_FILE"

# admin
ADMIN_BROADCAST = "ADMIN_BROADCAST"
ADMIN_RESTORE_FILE = "ADMIN_RESTORE_FILE"
ADMIN_RESTORE_CONFIRM = "ADMIN_RESTORE_CONFIRM"
